apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: camilowu/mi-app:0ac0a084f0c893672a07be0a61b77d2a5e7c7819
        ports:
        - containerPort: 80
